/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as AnalyzingJobIdRouteImport } from './routes/analyzing.$jobId'
import { Route as ApiAnalyzeSubmitRouteImport } from './routes/api/analyze.submit'
import { Route as ApiAnalyzeProcessRouteImport } from './routes/api/analyze.process'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzingJobIdRoute = AnalyzingJobIdRouteImport.update({
  id: '/analyzing/$jobId',
  path: '/analyzing/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeSubmitRoute = ApiAnalyzeSubmitRouteImport.update({
  id: '/api/analyze/submit',
  path: '/api/analyze/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeProcessRoute = ApiAnalyzeProcessRouteImport.update({
  id: '/api/analyze/process',
  path: '/api/analyze/process',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/analyzing/$jobId': typeof AnalyzingJobIdRoute
  '/report/$id': typeof ReportIdRoute
  '/api/analyze/process': typeof ApiAnalyzeProcessRoute
  '/api/analyze/submit': typeof ApiAnalyzeSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/analyzing/$jobId': typeof AnalyzingJobIdRoute
  '/report/$id': typeof ReportIdRoute
  '/api/analyze/process': typeof ApiAnalyzeProcessRoute
  '/api/analyze/submit': typeof ApiAnalyzeSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/analyzing/$jobId': typeof AnalyzingJobIdRoute
  '/report/$id': typeof ReportIdRoute
  '/api/analyze/process': typeof ApiAnalyzeProcessRoute
  '/api/analyze/submit': typeof ApiAnalyzeSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/analyzing/$jobId'
    | '/report/$id'
    | '/api/analyze/process'
    | '/api/analyze/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/analyzing/$jobId'
    | '/report/$id'
    | '/api/analyze/process'
    | '/api/analyze/submit'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/analyzing/$jobId'
    | '/report/$id'
    | '/api/analyze/process'
    | '/api/analyze/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  AnalyzingJobIdRoute: typeof AnalyzingJobIdRoute
  ReportIdRoute: typeof ReportIdRoute
  ApiAnalyzeProcessRoute: typeof ApiAnalyzeProcessRoute
  ApiAnalyzeSubmitRoute: typeof ApiAnalyzeSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzing/$jobId': {
      id: '/analyzing/$jobId'
      path: '/analyzing/$jobId'
      fullPath: '/analyzing/$jobId'
      preLoaderRoute: typeof AnalyzingJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze/submit': {
      id: '/api/analyze/submit'
      path: '/api/analyze/submit'
      fullPath: '/api/analyze/submit'
      preLoaderRoute: typeof ApiAnalyzeSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze/process': {
      id: '/api/analyze/process'
      path: '/api/analyze/process'
      fullPath: '/api/analyze/process'
      preLoaderRoute: typeof ApiAnalyzeProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  AnalyzingJobIdRoute: AnalyzingJobIdRoute,
  ReportIdRoute: ReportIdRoute,
  ApiAnalyzeProcessRoute: ApiAnalyzeProcessRoute,
  ApiAnalyzeSubmitRoute: ApiAnalyzeSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
