/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnfiledRouteImport } from './routes/unfiled'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatterIdRouteImport } from './routes/matter.$id'
import { Route as CaseIdRouteImport } from './routes/case.$id'
import { Route as AnalyzingJobIdRouteImport } from './routes/analyzing.$jobId'
import { Route as ApiSynthesizeSubmitRouteImport } from './routes/api/synthesize.submit'
import { Route as ApiSynthesizeProcessRouteImport } from './routes/api/synthesize.process'
import { Route as ApiAnalyzeSubmitRouteImport } from './routes/api/analyze.submit'
import { Route as ApiAnalyzeProcessRouteImport } from './routes/api/analyze.process'
import { Route as MatterMatterIdSynthesisSynthesisIdRouteImport } from './routes/matter.$matterId.synthesis.$synthesisId'

const UnfiledRoute = UnfiledRouteImport.update({
  id: '/unfiled',
  path: '/unfiled',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatterIdRoute = MatterIdRouteImport.update({
  id: '/matter/$id',
  path: '/matter/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseIdRoute = CaseIdRouteImport.update({
  id: '/case/$id',
  path: '/case/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzingJobIdRoute = AnalyzingJobIdRouteImport.update({
  id: '/analyzing/$jobId',
  path: '/analyzing/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSynthesizeSubmitRoute = ApiSynthesizeSubmitRouteImport.update({
  id: '/api/synthesize/submit',
  path: '/api/synthesize/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSynthesizeProcessRoute = ApiSynthesizeProcessRouteImport.update({
  id: '/api/synthesize/process',
  path: '/api/synthesize/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeSubmitRoute = ApiAnalyzeSubmitRouteImport.update({
  id: '/api/analyze/submit',
  path: '/api/analyze/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeProcessRoute = ApiAnalyzeProcessRouteImport.update({
  id: '/api/analyze/process',
  path: '/api/analyze/process',
  getParentRoute: () => rootRouteImport,
} as any)
const MatterMatterIdSynthesisSynthesisIdRoute =
  MatterMatterIdSynthesisSynthesisIdRouteImport.update({
    id: '/matter/$matterId/synthesis/$synthesisId',
    path: '/matter/$matterId/synthesis/$synthesisId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/unfiled': typeof UnfiledRoute
  '/analyzing/$jobId': typeof AnalyzingJobIdRoute
  '/case/$id': typeof CaseIdRoute
  '/matter/$id': typeof MatterIdRoute
  '/api/analyze/process': typeof ApiAnalyzeProcessRoute
  '/api/analyze/submit': typeof ApiAnalyzeSubmitRoute
  '/api/synthesize/process': typeof ApiSynthesizeProcessRoute
  '/api/synthesize/submit': typeof ApiSynthesizeSubmitRoute
  '/matter/$matterId/synthesis/$synthesisId': typeof MatterMatterIdSynthesisSynthesisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/unfiled': typeof UnfiledRoute
  '/analyzing/$jobId': typeof AnalyzingJobIdRoute
  '/case/$id': typeof CaseIdRoute
  '/matter/$id': typeof MatterIdRoute
  '/api/analyze/process': typeof ApiAnalyzeProcessRoute
  '/api/analyze/submit': typeof ApiAnalyzeSubmitRoute
  '/api/synthesize/process': typeof ApiSynthesizeProcessRoute
  '/api/synthesize/submit': typeof ApiSynthesizeSubmitRoute
  '/matter/$matterId/synthesis/$synthesisId': typeof MatterMatterIdSynthesisSynthesisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/unfiled': typeof UnfiledRoute
  '/analyzing/$jobId': typeof AnalyzingJobIdRoute
  '/case/$id': typeof CaseIdRoute
  '/matter/$id': typeof MatterIdRoute
  '/api/analyze/process': typeof ApiAnalyzeProcessRoute
  '/api/analyze/submit': typeof ApiAnalyzeSubmitRoute
  '/api/synthesize/process': typeof ApiSynthesizeProcessRoute
  '/api/synthesize/submit': typeof ApiSynthesizeSubmitRoute
  '/matter/$matterId/synthesis/$synthesisId': typeof MatterMatterIdSynthesisSynthesisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/unfiled'
    | '/analyzing/$jobId'
    | '/case/$id'
    | '/matter/$id'
    | '/api/analyze/process'
    | '/api/analyze/submit'
    | '/api/synthesize/process'
    | '/api/synthesize/submit'
    | '/matter/$matterId/synthesis/$synthesisId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/unfiled'
    | '/analyzing/$jobId'
    | '/case/$id'
    | '/matter/$id'
    | '/api/analyze/process'
    | '/api/analyze/submit'
    | '/api/synthesize/process'
    | '/api/synthesize/submit'
    | '/matter/$matterId/synthesis/$synthesisId'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/unfiled'
    | '/analyzing/$jobId'
    | '/case/$id'
    | '/matter/$id'
    | '/api/analyze/process'
    | '/api/analyze/submit'
    | '/api/synthesize/process'
    | '/api/synthesize/submit'
    | '/matter/$matterId/synthesis/$synthesisId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  UnfiledRoute: typeof UnfiledRoute
  AnalyzingJobIdRoute: typeof AnalyzingJobIdRoute
  CaseIdRoute: typeof CaseIdRoute
  MatterIdRoute: typeof MatterIdRoute
  ApiAnalyzeProcessRoute: typeof ApiAnalyzeProcessRoute
  ApiAnalyzeSubmitRoute: typeof ApiAnalyzeSubmitRoute
  ApiSynthesizeProcessRoute: typeof ApiSynthesizeProcessRoute
  ApiSynthesizeSubmitRoute: typeof ApiSynthesizeSubmitRoute
  MatterMatterIdSynthesisSynthesisIdRoute: typeof MatterMatterIdSynthesisSynthesisIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unfiled': {
      id: '/unfiled'
      path: '/unfiled'
      fullPath: '/unfiled'
      preLoaderRoute: typeof UnfiledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matter/$id': {
      id: '/matter/$id'
      path: '/matter/$id'
      fullPath: '/matter/$id'
      preLoaderRoute: typeof MatterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$id': {
      id: '/case/$id'
      path: '/case/$id'
      fullPath: '/case/$id'
      preLoaderRoute: typeof CaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzing/$jobId': {
      id: '/analyzing/$jobId'
      path: '/analyzing/$jobId'
      fullPath: '/analyzing/$jobId'
      preLoaderRoute: typeof AnalyzingJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/synthesize/submit': {
      id: '/api/synthesize/submit'
      path: '/api/synthesize/submit'
      fullPath: '/api/synthesize/submit'
      preLoaderRoute: typeof ApiSynthesizeSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/synthesize/process': {
      id: '/api/synthesize/process'
      path: '/api/synthesize/process'
      fullPath: '/api/synthesize/process'
      preLoaderRoute: typeof ApiSynthesizeProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze/submit': {
      id: '/api/analyze/submit'
      path: '/api/analyze/submit'
      fullPath: '/api/analyze/submit'
      preLoaderRoute: typeof ApiAnalyzeSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze/process': {
      id: '/api/analyze/process'
      path: '/api/analyze/process'
      fullPath: '/api/analyze/process'
      preLoaderRoute: typeof ApiAnalyzeProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matter/$matterId/synthesis/$synthesisId': {
      id: '/matter/$matterId/synthesis/$synthesisId'
      path: '/matter/$matterId/synthesis/$synthesisId'
      fullPath: '/matter/$matterId/synthesis/$synthesisId'
      preLoaderRoute: typeof MatterMatterIdSynthesisSynthesisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  UnfiledRoute: UnfiledRoute,
  AnalyzingJobIdRoute: AnalyzingJobIdRoute,
  CaseIdRoute: CaseIdRoute,
  MatterIdRoute: MatterIdRoute,
  ApiAnalyzeProcessRoute: ApiAnalyzeProcessRoute,
  ApiAnalyzeSubmitRoute: ApiAnalyzeSubmitRoute,
  ApiSynthesizeProcessRoute: ApiSynthesizeProcessRoute,
  ApiSynthesizeSubmitRoute: ApiSynthesizeSubmitRoute,
  MatterMatterIdSynthesisSynthesisIdRoute:
    MatterMatterIdSynthesisSynthesisIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
