/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as ApiAnalyzeSubmitRouteImport } from './routes/api/analyze.submit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeSubmitRoute = ApiAnalyzeSubmitRouteImport.update({
  id: '/api/analyze/submit',
  path: '/api/analyze/submit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/report/$id': typeof ReportIdRoute
  '/api/analyze/submit': typeof ApiAnalyzeSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/report/$id': typeof ReportIdRoute
  '/api/analyze/submit': typeof ApiAnalyzeSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/report/$id': typeof ReportIdRoute
  '/api/analyze/submit': typeof ApiAnalyzeSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/report/$id' | '/api/analyze/submit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/report/$id' | '/api/analyze/submit'
  id: '__root__' | '/' | '/report/$id' | '/api/analyze/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportIdRoute: typeof ReportIdRoute
  ApiAnalyzeSubmitRoute: typeof ApiAnalyzeSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze/submit': {
      id: '/api/analyze/submit'
      path: '/api/analyze/submit'
      fullPath: '/api/analyze/submit'
      preLoaderRoute: typeof ApiAnalyzeSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportIdRoute: ReportIdRoute,
  ApiAnalyzeSubmitRoute: ApiAnalyzeSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
